Core/urls.py
from django.urls import path, include

from .views import index

urlpatterns = [
   path('', index, name = 'index')
]

Pessoa/urls.py
from django.urls import path, include

from .views import pessoa

urlpatterns = [
   path('view/', pessoa, name = 'pessoa')
]

Profissao/urls.py
from django.urls import path, include

from .views import profissao

urlpatterns = [
   path('view/', profissao, name = 'profissao')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Core.urls', 'index'), namespace='index')),
    path('pessoas/', include(('Pessoa.urls', 'pessoas'), namespace='pessoas')),
    path('profissoes/', include(('Profissao.urls', 'profissoes'), namespace='profissoes')),
]

Core/models.py
from django.db import models

# Create your models here.

Pessoa/models.py
from django.db import models

from Profissao.models import Profissao

class Pessoa(models.Model):
   id = models.AutoField(primary_key = True)
   nome = models.CharField(max_length = 150)
   profissao = models.ForeignKey(
      Profissao, on_delete=models.CASCADE, blank=True, null=True
   )

   class Meta:
      app_label = 'Pessoa'
      db_table = 'pessoas'

   def __str__(self):
      return self.nome

Profissao/models.py
from django.db import models

class Profissao(models.Model):
   id = models.AutoField(primary_key = True)
   profissao = models.CharField(max_length = 100)

   class Meta:
      app_label = 'Profissao'
      db_table = 'profissoes'

   def __str__(self):
      return self.profissao

Pessoa/forms.py
from django import forms

from .models import Pessoa
from Profissao.models import Profissao

class PessoaForm(forms.ModelForm):
   nome = forms.CharField(required = True, widget=forms.TextInput())
   profissao = forms.ModelChoiceField(required = True, queryset=Profissao.objects.using('profissoes_db').all(),\
      empty_label='Selecione uma profissao...', \
   )

   class Meta:
      model = Pessoa
      fields = '__all__'

class SearchForm(forms.ModelForm):
   search = forms.CharField(required=False, widget=forms.TextInput())

   class Meta:
      model = Pessoa
      fields = ['search']

Profissao/forms.py
from django import forms

from .models import Profissao

class ProfissaoForm(forms.ModelForm):
   profissao = forms.CharField(widget=forms.TextInput())

   class Meta:
      model = Profissao
      fields = '__all__'

class SearchForm(forms.ModelForm):
    search = forms.CharField(required=False, widget=forms.TextInput())

    class Meta:
        model = Profissao
        fields = ['search']

Core/views.py
from django.shortcuts import render

def index(request):
   return render(request, 'index.html')

Pessoa/views.py
from django.shortcuts import render
import json

from .models import Pessoa
from .forms import PessoaForm, SearchForm

def pessoa(request):
   form = PessoaForm(request.POST or None)
   listagem = Pessoa.objects.using('pessoas_db').all()
   search = SearchForm(request.POST or None)

   if request.method == 'POST':
      if form.is_valid():
         form.save()

   busca = request.GET.get('search')
   if busca:
      listagem = Pessoa.objects.using('pessoas_db').filter(nome__icontains = busca)
      
      rows = len(listagem)
      if rows == 0:
         print("Sem registros!")
      else:
         for busca in listagem:
            print(busca.profissao)
            
   params = {
      'form': form,
      'listagem': listagem,
      'search': search
   }

   return render(request, 'pessoa.html', params)

Profissao/views.py
from django.shortcuts import render

from .forms import ProfissaoForm, SearchForm
from .models import Profissao

def profissao(request):
   form = ProfissaoForm(request.POST or None)
   listagem = Profissao.objects.using('profissoes_db').all()
   search = SearchForm(request.POST or None)

   if request.method == 'POST':
      if form.is_valid():
         form.save()

   busca = request.GET.get('search')
   if busca:
      listagem = Profissao.objects.using('profissoes_db').filter(profissao__icontains=busca)

   params = {
      'form': form,
      'listagem': listagem,
      'search': search,
   }

   return render(request, 'profissao.html', params)

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Multiple Databases with Django 2.0</title>
   </head>
   
   <body>
      <header style="text-align: center;">
         <h1>Studying multiple databases with Django</h1>
         <small>
            <p>created by: Wendrew Soares de Oliveira</p>
         </small>
      </header>

      <hr><br>

      <a href="{% url 'profissoes:profissao' %}">Cadastrar profissão</a> | 
      <a href="{% url 'pessoas:pessoa' %}">Cadastrar pessoa</a>

   </body>
</html>

templates/pessoa.html
<!DOCTYPE html>
<html lang="pt-br">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Multiple Databases with Django 2.0</title>
   </head>
   <body>
      <header>
         <h1>Pessoa view</h1><br>
         <a href="{% url 'profissoes:profissao' %}">Cadastrar profissao</a> | 
         <a href="{% url 'index:index' %}">Inicio</a>
      </header>

      <hr>

      <form action="{% url 'pessoas:pessoa' %}" method="POST">
         {% csrf_token %}
         {{form.as_p}}
         <button type="submit">Salvar</button>
      </form>

      <hr>
      
      <table>
         <thead>
            <tr>
               <th>#</th>
               <th>Nome</th>
               <th>Profissão</th>
            </tr>
         </thead>
         <tbody>
            {% for value in listagem %}
            <tr>
               <th>
                  <td>{{value.id}}</td>
                  <td>{{value.nome}}</td>
                  <td>{{value.profissao}}</td>
               </th>
            </tr>
            {% endfor %}
         </tbody>
      </table>

      <hr>

      <div>
         <form method="GET">
            {{search.as_p}}
            <button type="submit">Buscar</button>
         </form>
      </div>

   </body>
</html>

templates/profissao.html
<!DOCTYPE html>
<html lang="pt-br">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Multiple Databases with Django 2.0</title>
   </head>
   <body>
      <header>
         <h1>Profissao view</h1><br>
         <a href="{% url 'pessoas:pessoa' %}">Cadastrar pessoa</a> | 
         <a href="{% url 'index:index' %}">Inicio</a>
      </header>

      <hr>

      <form action="{% url 'profissoes:profissao' %}" method="POST">
         {% csrf_token %}
         {{form.as_p}}
         <button type="submit">Salvar</button>
      </form>

      <hr>
      
      <table>
         <thead>
            <tr>
               <th>#</th>
               <th>Profissao</th>
            </tr>
         </thead>
         <tbody>
            {% for value in listagem %}
            <tr>
               <th>
                  <td>{{value.id}}</td>
                  <td>{{value.profissao}}</td>
               </th>
            </tr>
            {% endfor %}
         </tbody>
      </table>

      <hr>

      <div>
         <form method="GET">
            {{search.as_p}}
            <button type="submit">Buscar</button>
         </form>
      </div>

   </body>
</html>